USE FORO;

CREATE TABLE USER (
    ID BINARY(16) DEFAULT (UUID_TO_BIN(UUID(), 1)) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
)

CREATE TABLE THREAD (
    ID BINARY(16) DEFAULT (UUID_TO_BIN(UUID(), 1)) PRIMARY KEY,
    USER_ID BINARY(16) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
)

CREATE TABLE THREAD_MSG (
    ID BINARY(16) DEFAULT (UUID_TO_BIN(UUID(), 1)) PRIMARY KEY,
    ID_THREAD BINARY(16) NOT NULL,
    ID_USER BINARY(16) NOT NULL,
    MSG TEXT NOT NULL,
    FOREIGN KEY (ID_THREAD) REFERENCES THREAD(ID),
    FOREIGN KEY (ID_USER) REFERENCES USER(ID)
)
